app:
  name: dss-demo
dss:
  username: admin
  password: 12345678
  convert:
    clear-inactive-task-cron: 0 0/2 * * * ? # 清理不活跃转流任务cron，暂设2分钟
    keep-alive-time: 300 # 保活时间，单位: 秒
    rtmp-url-prefix: rtmp://192.168.164.188:1935/hls/ # rtmp地址前缀
    hls-url-tmplate: http://192.168.164.188:8080/hls/SEQ/index.m3u8 # hls流地址模板
    job-limit: 10 # 转流任务上限, 该值的设定必须大于0才有效
    image-width: 1280
    image-height: 720
    tune: zerolatency
    crf: 28
    preset: ultrafast
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  profiles:
    active: dev